countingsort:countingsort.py
	python3 countingsort.py

bucketsort:bucketsort.py
	python3 bucketsort.py

radixsort:radixsort.py
	python3 radixsort.py

wordsort:implement_word.py
	python3 implement_word.py

